[package]
name = "cf-worker"
version = "0.1.1"
authors = ["Floris Cornel <floris@cornel.email>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.0.12"
wordle-assistant = { path = "../", features = ["api_code"] }

[profile.release]
opt-level = "s"
