name: Cloudflare Worker

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Build & Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cf-worker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features=all -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - run: yarn global add wrangler
      - run: wrangler publish
