name: Cloudflare Worker

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  wrangler-build-push:
    name: Wrangler Build & Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cf-worker
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: yarn global add wrangler

      - name: Install Rust toolchain (wasm32)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: "wasm32-unknown-unknown"

      - name: Configure cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "wordle-assistant"
          workspaces: |
            .
            ./cf-worker

      - name: Wrangler Build
        run: wrangler publish --dry-run

      - name: Wrangler Publish
        run: wrangler publish
