name: Cloudflare Worker

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  deploy:
    name: Build & Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cf-worker
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - name: Check for type errors
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check Clippy lints
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features=all -- -D warnings

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Install Wrangler
        run: yarn global add wrangler

      - name: Wrangler Build
        run: wrangler publish --dry-run

      - name: Wrangler Publish
        run: wrangler publish
